1/mysite/blog/urls.py
from django.conf.urls import url
from blog import views


urlpatterns = [
    # post views
    url(r'^$', views.post_list, name='post_list'),
    #url(r'^$', views.PostListView.as_view(), name='post_list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$',
        views.post_detail,
        name='post_detail'),
    url(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),
    url(r'^(?P<tag_slug>[-\w]+)/$', views.post_list, name='post_list_by_tag')
    ]

1/mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap


sitemaps = {
    'posts': PostSitemap,
}


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.vies.sitemap'),
]

1/mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):

    def __call__(self):
        print(1)

    def get_queryset(self):
        return super().get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.strftime('%m'),
                             self.publish.strftime('%d'),
                             self.slug])


class Comment(models.Model):

    post = models.ForeignKey(Post, related_name='comments')
    name = models.CharField(max_length=80)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    body = models.TextField()
    email = models.EmailField()
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

1/mysite/blog/forms.py
from django import forms
from .models import Comment


class EmailPostFrom(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)


class CommentPost(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

1/mysite/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from blog.models import Post, Comment
from django.views.generic import ListView
from .forms import EmailPostFrom, CommentPost
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request,
                  'blog/post/list.html',
                  {'page': page,
                   'posts': posts,
                   'tag': tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)

    post_tags_id = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_id)\
                                .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
                                 .order_by('-same_tags', '-publish')[:4]

    new_comment = None
    comments = post.comments.all()

    if request.method == 'POST':
        comment_form = CommentPost(request.POST)
        if comment_form.is_valid:
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            #new_comment.active = False
            new_comment.save()

    else:
        comment_form = CommentPost()

    return render(request,
                  'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'comment_form': comment_form,
                   'new_comment': new_comment,
                   'similar_posts': similar_posts})


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    cd = None

    if request.method == 'POST':
        form = EmailPostFrom(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading {}'.format(
                cd['name'], cd['email'], post.title)
            msg = 'Read "{}" at {}\n{}\'s comments: {}'.format(
                post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, msg, 'ivelintod@gmail.com', [cd['to']])
            sent = True

    else:
        form = EmailPostFrom()

    return render(request, 'blog/post/share.html',
                  {'post': post,
                   'form': form,
                   'sent': sent,
                   'cd': cd})


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'

1/mysite/blog/templates/blog/base.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/blog.css" %}" rel='stylesheet'>
</head>
<body>
    <div id='content'>
        {% block content %}
        {% endblock %}
    </div>
    <div id='sidebar'>
        <h2>My Blog</h2>
          <p>This is my blog. So far I have written {% total_posts %} posts.</p>
        <h3>Latest Posts</h3>
        {% show_latest_posts 3 %}
        <h3>Most Commented Posts</h3>
        {% get_most_commented_posts as most_commented_posts %}
        <ul>
          {% for post in most_commented_posts %}
            <li>
              <a href='{{ post.get_absolute_url }}'> {{ post.title }}</a>
            </li>
          {% endfor %}
        </ul>
    </div>
</body>
</html>

1/mysite/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %} {{ post.title }} {% endblock %}

{% block content %}
  <h1>{{ post.title }}</h1>
  <p class="date">
    Published {{ post.publish }} by {{ post.author }}
  </p>
  <p class='tags'>
    Tags:
      {% for tag in post.tags.all %}
        <a href='{% url "blog:post_list_by_tag" tag.slug %}'>{{ tag.name }}</a>
        {% if not forloop.last %}, {% endif %}
      {% empty %}
        No tags
      {% endfor %}
  </p>
  </p>
  {{ post.body|markdown }}

  <span>
    <a href="{% url 'blog:post_share' post.id %}">
      Share this post
    </a>
  </span>

  <div>
    <h1>Similar Posts</h1>
    {% for post in similar_posts %}
      <a href='{{ post.get_absolute_url }}'>{{ post.title }}
      </a>
    {% empty %}
      There are no similar posts yet.
    {% endfor %}
  </div>

  {% with comments.count as total_comments %}
    <h2>
      {{ total_comments }} comment{{ total_comments|pluralize }}
    </h2>
  {% endwith %}

  {% for comment in comments %}
    <div class='comment'>
      <p class="{% cycle 'info' 'info2' %}">
        Comment {{ forloop.counter }} by {{ comment.name }}, {{ comment.created }}
      </p>
        {{ comment.body|linebreaks }}

    </div>
  {% empty %}
    <p>There are no comments yet.</p>
  {% endfor %}

  {% if new_comment %}
    <h2>Your comment has been added.</h2>
  {% else %}
    <h2>Add a new comment</h2>
    <form action='.' method='POST'>
      {{ comment_form.as_p }}
      {% csrf_token %}
      <p><input type='submit' value='Add comment'></p>
    </form>
  {% endif %}

{% endblock %}

1/mysite/blog/templates/blog/post/latest_posts.html
<ul>
  {% for post in latest_posts %}
    <li>
      <a href="{{ post.get_absolute_url }}"> {{ post.title }} </a>
    </li>
  {% endfor %}
</ul>

1/mysite/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %} My Blog {% endblock %}

{% block content %}
    <h1>My Blog</h1>
    {% if tag %}
      <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
            <p class='tags'>
              Tags:
              {% for tag in post.tags.all %}
                <a href='{% url "blog:post_list_by_tag" tag.slug %}'> {{ tag.name }}
                </a>
                {% if not forloop.last %}, {% endif %}
              {% endfor %}
            </p>
        </h2>
        <p class='date'>
            Published {{ post.publish }} by {{ post.author}}
        </p>
        {{ post.body|markdown|truncatewords_html:30 }}
    {% endfor %}
    {% include "pagination.html" with page=posts %}
{% endblock %}

1/mysite/blog/templates/blog/post/pagination.html
<div class='pagination'>
    <span class='step-links'>
    {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class='current'>
        Page {{ page.number }} of {{ page.paginator.num_pages }}
    </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

1/mysite/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
  {% if sent %}
    <h1>Email sent successfully!</h1>
    <p>
      "{{ post.title }}" was successfully sent to {{ cd.to }}.
    </p>

  {% else %}
    <h1>Share "{{ post.title }}" by email</h1>
    <form action="." method="post">
      {% for field in form %}
        <div>
          {{ field.errors }}
          {{ field.label_tag }} {{ field }}
        </div>
      {% endfor %}
      {% csrf_token %}
      <input type="submit" value="Send email">
    </form>
  {% endif %}
{% endblock %}

1/mysite/blog/templates/pagination.html
<div class='pagination'>
    <span class='step-links'>
    {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class='current'>
        Page {{ page.number }} of {{ page.paginator.num_pages }}
    </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>